ci: Install a single package only with pip.
Latest pip version raises a conflict running `pip install dist/*` :

$ pip install dist/*
Processing ./dist/python-musicpd-0.4.5.tar.bz2
Processing ./dist/python-musicpd-0.4.5.tar.gz
ERROR: Cannot install python-musicpd 0.4.5 (from /builds/kaliko/python-musicpd/dist/python-musicpd-0.4.5.tar.bz2) and python-musicpd 0.4.5 (from /builds/kaliko/python-musicpd/dist/python-musicpd-0.4.5.tar.gz) because these package versions have conflicting dependencies.
The conflict is caused by:
    The user requested python-musicpd 0.4.5 (from /builds/kaliko/python-musicpd/dist/python-musicpd-0.4.5.tar.bz2)
    The user requested python-musicpd 0.4.5 (from /builds/kaliko/python-musicpd/dist/python-musicpd-0.4.5.tar.gz)
To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict
ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies